spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: cypriani
  flyway:
    baselineOnMigrate: 'true'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
