spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: cypriani
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
  flyway:
    fail-on-missing-locations: true
    baselineOnMigrate : true
